from datetime import date, datetime
from decimal import Decimal
from typing import Optional

from pydantic import BaseModel, Field


class AssetRead(BaseModel):
    id: int
    code: str
    name: str
    asset_type: str
    market: Optional[str] = None
    theme: Optional[str] = None

    model_config = {"from_attributes": True}


class HoldingRead(BaseModel):
    id: int
    asset: AssetRead
    amount: Decimal
    units: Optional[Decimal] = None
    cost_basis: Optional[Decimal] = None
    profit: Optional[Decimal] = None
    last_valuation_at: Optional[datetime] = None
    last_valuation_source: Optional[str] = None
    last_manual_adjustment_at: Optional[datetime] = None
    last_manual_adjustment_reason: Optional[str] = None
    last_update_type: Optional[str] = None
    manual_adjusted: bool = False

    model_config = {"from_attributes": True}


class HoldingUpdate(BaseModel):
    """Fields that can be corrected when the broker statement has changed."""

    amount: Optional[Decimal] = Field(default=None, ge=0)
    units: Optional[Decimal] = Field(default=None, ge=0, decimal_places=2)
    cost_basis: Optional[Decimal] = Field(default=None, ge=0)
    profit: Optional[Decimal] = None
    correction_reason: Optional[str] = Field(default=None, max_length=500)


class TransactionCreate(BaseModel):
    asset_code: str
    asset_type: str = "fund"
    asset_name: Optional[str] = None
    operation: str = Field(pattern="^(buy|sell|dividend|transfer|adjustment|note)$")
    trade_date: date
    amount: Decimal = Field(ge=0)
    units: Optional[Decimal] = Field(default=None, ge=0, decimal_places=2)
    price: Optional[Decimal] = Field(default=None, ge=0)
    fee: Decimal = Field(default=0, ge=0)
    reason: Optional[str] = None


class TransactionRead(BaseModel):
    id: int
    asset: AssetRead
    operation: str
    trade_date: date
    amount: Decimal
    units: Optional[Decimal] = None
    price: Optional[Decimal] = None
    fee: Decimal
    reason: Optional[str] = None
    created_at: datetime
    retracted_at: Optional[datetime] = None
    retraction_reason: Optional[str] = None
    retraction_effect: Optional[str] = None

    model_config = {"from_attributes": True}


class ImportHoldingsRequest(BaseModel):
    path: str


class ImportHoldingsResponse(BaseModel):
    imported: int
    skipped: int


class WatchlistCreate(BaseModel):
    name: str
    description: Optional[str] = None


class WatchlistItemCreate(BaseModel):
    asset_code: str
    asset_type: str = "fund"
    asset_name: Optional[str] = None


class WatchlistItemUpdate(BaseModel):
    custom_name: Optional[str] = Field(default=None, max_length=255)
    tags: Optional[list[str]] = Field(default=None, max_length=12)


class WatchlistRefreshRequest(BaseModel):
    item_ids: list[int] = Field(min_length=1, max_length=50)


class KnowledgeSearchResult(BaseModel):
    title: str
    content: str
    source_path: str
    score: int


class AgentNoteCreate(BaseModel):
    title: str
    content: str
    note_date: date
    source: str = "agent"


class ReviewAppendRequest(BaseModel):
    """Markdown generated by an external analysis agent for direct append."""

    analysis_date: date
    content: str = Field(min_length=1, max_length=200_000)
    run_id: Optional[str] = Field(default=None, max_length=120)
